#!/bin/bash

# jdbimp -- Import a sql file into a Joomla database.
# Supports Joomla versions 2.5 - 3.x
#
# Copyright 2014 - 2024 René Kreijveld - email@renekreijveld.nl
#
# This program is free software; you may redistribute it and/or modify it.
#
# Warning! This script needs the file jfunctions. This has to be installed in the same directory as this script.
#
# Version history
# 1.0 Initial version
# 1.1 Code rewrite
# 1.2 Modification of all echo -e statements
# 1.3 Added test if jfunctions exists
# 1.4 Code improvements

# Constants
VERSION=1.4
MYPATH=$(cd "$(dirname "$0")"; pwd -P)
MYNAME=$(basename "$0")

# Function to show messages (honoring silent mode)
showmessage() {
    if [[ "${SILENT}" == "no" ]]; then
        echo "$1"
    fi
}

# Check if jfunctions script exists
if [[ ! -f "${MYPATH}/jfunctions" ]]; then
    echo "Error: Required script 'jfunctions' not found in ${MYPATH}. Exiting."
    exit 1
else
    # Gather Joomla information
    source "${MYPATH}/jfunctions"
fi

# Display usage information
usage() {
    echo ""
    echo "${MYNAME} version ${VERSION}, written by Rene Kreijveld."
    echo ""
    echo "Usage: ${MYNAME} [-s] [-h]"
    echo ""
    echo "-s Silent. Display no messages"
    echo "-h Help. Display this info."
    echo ""
    exit 0
}

# Process the arguments
SILENT="no"
while getopts "sh" opt; do
    case "${opt}" in
        s) SILENT="yes" ;;
        h) usage ;;
        *) usage ;;
    esac
done

showmessage "${MYNAME} version ${VERSION}, written by René Kreijveld."

# Check if database dump exists.
if [[ ! -f ${database}.sql ]]; then
	echo "Error: database dump file not found. The filemname should be ${database}.sql. Exiting."
	exit 1
fi

if mysql --host=${host} --user=${dbuser} --password=${password} ${database} < ${database}.sql; then
    showmessage "${database}.sql imported."
else
    echo "Error importing database dump."
    exit 1
fi