#!/bin/bash

# joomlainfo -- Provide information about this Joomla! installation.
# Supports Joomla 1.0 - 3.x
#
# Copyright 2014 - 2024 Rene Kreijveld - email@renekreijveld.nl
#
# This program is free software; you may redistribute it and/or modify it.
#
# This script uses the 'jfunctions' script to extract information about a Joomla installation.
# The jfunctions script must be in the same folder as where this script is saved.
#
# Version history
# 1.0 Initial version
# 1.1 Code rewrite
# 1.2 Modification of all echo -e statements
# 1.3 Added test if jfunctions exists
# 1.4 Updated display of version number for joomla 4 and up
# 1.5 Code optimisations

# General variables
MYPATH=$(cd "$(dirname "${0}")" && pwd -P)
MYNAME=$(basename "${0}")
VERSION=1.5

# Include general functions
if [[ ! -e "${MYPATH}/jfunctions" ]]; then
    printf "\nError: Cannot continue. Script 'jfunctions' not found in ${MYPATH}.\n"
    exit 1
else
    # shellcheck source=/dev/null
    source "${MYPATH}/jfunctions"
fi

# Output information
printf "\n${MYNAME} version ${VERSION}, written by Rene Kreijveld.\n\n"
printf "This Joomla website:\n"
printf "Sitename    : ${sitenameclean}\n"
printf "Version     : ${jversion}\n"
printf "DB Name     : ${database}\n"
printf "DB User     : ${dbuser}\n"
printf "DB Password : ${password}\n"
printf "DB Host     : ${host}\n"
printf "DB Prefix   : ${prefix}\n"
printf "Path        : $(pwd)\n\n"
