#!/bin/sh

# jdbsession -- Repair the session table of a Joomla database table.
#
# This scripts supports Joomla versions 1.0 - 3.3
#
# Copyright 2014 Rene Kreijveld - r.kreijveld@gakijken.nl
#
# This program is free software; you may redistribute it and/or modify it.
#
# Warning! This script needs the file joomlafunctions. This has to be installed in the same directory as this script.
#
# Version history
# 3.0 Initial version
# 3.1 Added -a option
# 3.2 Added version history
# 3.3 Added -c option to just check the database

# General variables
mypath=$(cd $(dirname ${0}); pwd -P)
myname=$(basename ${0})
startdir=/home

# Version
version=3.3

# display usage information
usage() {
	echo ""
	echo "${myname} version ${version}, written by Rene Kreijveld."
	echo ""
	echo "Usage: ${myname} [-a] [-h]\n"
	echo "-a All. Repair session tables for all Joomla websites found."
	echo "-h Help. Display this info."
	echo ""
	echo "If used without the -a option, ${myname} should be run in the root of your Joomla website.\n"
	echo ""
	exit 0
}

sessionRepair() {
	# get Joomla info
	. ${mypath}/jfunctions
	repair="--repair"
	rtext="Repairing"
	if [ "${check}" == "yes" ]; then
		repair=""
		rtext="Checking"
	fi
	echo "${rtext} session table for ${sitename}:"
	mysqlcheck --user=${dbuser} --password=${password} ${repair} ${database} ${prefix}session
}

# process the arguments
all="no"
check="no"
while getopts ach opt
do
	case "${opt}" in
		a) all="yes";;
		c) check="yes";;
		h) usage;;
		\?) usage;;
	esac
done

echo ""
echo "${myname} version ${version}, written by Rene Kreijveld."
echo ""

if [ "${all}" == "yes" ]; then
	for dir in `find ${startdir} -maxdepth 4 -type d -name "public_html"`; do
		if [ -f ${dir}/configuration.php ]; then
			# possible joomla found
			echo "Joomla website found at ${dir}"
			cd ${dir}
			sessionRepair;
		fi
	done
else
	sessionRepair;
fi