#!/bin/sh

# jinfo -- Provide information about this Joomla! installation.
# Supports Joomla 1.0 - 3.3
#
# Copyright 2014 Rene Kreijveld - r.kreijveld@gakijken.nl
#
# This program is free software; you may redistribute it and/or modify it.
#
# Warning! This script needs the file jfunctions. This has to be installed in the same directory as this script.
#
# Version history
# 3.0 Initial version
# 3.1 Code rewrite
# 3.2 Modification of all echo -e statements

# general variables
mypath=$(cd $(dirname ${0}); pwd -P)
myname=$(basename ${0})

# include general functions
. ${mypath}/jfunctions

# version
version=3.2

echo ""
echo "${myname} verion ${version}, written by Rene Kreijveld."
echo ""

# output information
echo "This Joomla! website:"
echo "Sitename    :" $sitenameclean
echo "Version     :" $versr.$versd $verss
echo "DB Name     :" $database
echo "DB User     :" $dbuser
echo "DB Password :" $password
echo "DB Host     :" $host
echo "DB Prefix   :" $prefix
echo "Path        :" `pwd`
echo ""