#!/bin/sh

# jinfo -- Provide information about this Joomla! installation.
# Supports Joomla 1.0 - 3.3
#
# Copyright 2014 Rene Kreijveld - r.kreijveld@gakijken.nl
#
# This program is free software; you may redistribute it and/or modify it.
#
# Warning! This script needs the file jfunctions. This has to be installed in the same directory as this script.

# General variables
mypath=$( cd $(dirname ${0}) ; pwd -P )
myname=`basename ${0}`

# Include general functions
. ${mypath}/jfunctions

# Version
version=3.1
echo -e "\n${myname} verion ${version}, written by Rene Kreijveld.\n"

# Output information
echo "This Joomla! website:"
echo "Sitename    :" $sitenameclean
echo "Version     :" $versr.$versd $verss
echo "DB Name     :" $database
echo "DB User     :" $dbuser
echo "DB Password :" $password
echo "DB Host     :" $host
echo "DB Prefix   :" $prefix
echo "Path        :" `pwd`