#!/bin/sh

# jlistjoomlas -- Find Joomla instances on your (DirectAdmin based) server.
# Supports Joomla versions 1.0 - 3.3
#
# Copyright 2014 Rene Kreijveld - r.kreijveld@gakijken.nl
#
# This program is free software; you may redistribute it and/or modify it.
#
# Warning! This script needs the file jfunctions. This has to be installed in the same directory as this script.
#
# Version history
# 3.0 Initial version
# 3.1 Code rewrite
# 3.2 Added CSV option
# 3.3 Modification of all echo -e statements

# define variables
version=3.3
mypath=$(cd $(dirname ${0}); pwd -P)
myname=$(basename ${0})
startdir=/home

# display usage information
usage() {
	echo ""
	echo "${myname} version ${version}, written by Rene Kreijveld."
	echo ""
	echo "Usage: ${myname} [-s] [-c] [-h]"
	echo ""
	echo "-s Short. Only display path and Joomla version."
	echo "-c CSV. Output values in CSV format."
	echo "-h Help. Display this info."
	echo ""
	echo "Example usage:"
	echo ""
	echo "${myname}"
	echo "Outputs detailed information about Joomla websites found on this server."
	echo ""
	echo "${myname} -c > joomlasites.csv"
	echo "Outputs detailed information about Joomla websites in CSV format and writes result to the file joomlasites.csv."
	echo ""
	exit 0
}

# process the arguments
short="no"
csv="no"
while getopts sch opt
do
	case "${opt}" in
		s) short="yes";;
		c) csv="yes";;
		h) usage;;
		\?) usage;;
	esac
done

if [ "${csv}" == "no" ]; then
	if [ "${short}" == "no" ]; then
		echo ""
		echo "${myname} version ${version}, written by Rene Kreijveld."
		echo ""
	fi
fi

if [ "${csv}" == "yes" ]; then
	echo "\"map\",\"name\",\"version\",\"database\",\"dbuser\",\"password\",\"host\",\"prefix\""
fi

for dir in $(find ${startdir} -maxdepth 4 -type d -name "public_html")
do
	if [ -f ${dir}/configuration.php ]; then
		# possible joomla found
		cd ${dir}
		if [ "${csv}" == "no" ]; then
			if [ "${short}" == "no" ]; then
				echo Possible Joomla found in ${dir}
			fi
		fi

		# get Joomla information
		. ${mypath}/jfunctions

		# output information
		if [ "${csv}" == "yes" ]; then
			echo "\"${dir}\",\"${sitename}\",\"${versr}.${versd} ${verss}\",\"${database}\",\"${dbuser}\",\"${password}\",\"${host}\",\"${prefix}\""
		else
			if [ "${short}" == "no" ]; then
				echo "Joomla information found:"
				echo "Sitename    : ${sitename}"
				echo "Version     : ${versr}.${versd} ${verss}"
				echo "DB Name     : ${database}"
				echo "DB User     : ${dbuser}"
				echo "DB Password : ${password}"
				echo "DB Host     : ${host}"
				echo "DB Prefix   : ${prefix}"
				echo ""
			else
				echo "Joomla found in ${dir}"
				echo "Version: ${versr}.${versd} ${verss}"
				echo ""
			fi
		fi
	fi
done