#!/bin/sh

# jlistakeeba -- Find Akeeba backupson your (DirectAdmin based) server.
# Supports Joomla versions 2.5 - 3.5
#
# Copyright 2016 Rene Kreijveld - r.kreijveld@gakijken.nl
#
# This program is free software; you may redistribute it and/or modify it.
#
# Warning! This script needs the file jfunctions. This has to be installed in the same directory as this script.
#
# Version history
# 1.0 Initial version

# define variables
version=1.0
mypath=$(cd $(dirname ${0}); pwd -P)
myname=$(basename ${0})
startdir=/home

# display usage information
usage() {
	echo ""
	echo "${myname} version ${version}, written by Rene Kreijveld."
	echo ""
	echo "Usage: ${myname} [-h]"
	echo ""
	echo "-h Help. Display this info."
	echo ""
	exit 0
}

# process the arguments
short="no"
csv="no"
releaseversion=
while getopts schr: opt
do
	case "${opt}" in
		h) usage;;
		\?) usage;;
	esac
done

echo "${myname} version ${version}, written by Rene Kreijveld."
echo ""

for dir in $(find ${startdir} -maxdepth 4 -type d -name "public_html")
do
	if [ -f ${dir}/configuration.php ]; then
		# possible joomla found
		cd ${dir}
		echo Possible Joomla found in ${dir}

		# output found .jpa files
		find . -type f -name "*.jpa" -exec ls -l {} \; | grep -v angie

	fi
done