#!/bin/bash

# joomlainfo -- Provide information about this Joomla! installation.
# Supports Joomla 1.0 - 4.x
#
# Copyright 2014 - 2022 Rene Kreijveld - email@renekreijveld.nl
# This program is free software; you may redistribute it and/or modify it.
#
# Warning! This script needs the file jfunctions. This has to be installed in the same directory as this script.
#
# Version history
# 1.0 Initial version
# 1.1 Code rewrite
# 1.2 Modification of all echo -e statements
# 1.3 Added test if jfunctions exists

# general variables
mypath=$(cd $(dirname ${0}); pwd -P)
myname=$(basename ${0})

# include general functions
if [ ! -e ${mypath}/jfunctions ]
then
	echo ""
	echo "Cannot continue: script jfunctions not found."
	echo ""
	exit 1
else
	. ${mypath}/jfunctions
fi

# version
version=1.3

echo ""
echo "${myname} verion ${version}, written by Rene Kreijveld."
echo ""

# output information
echo "This Joomla! website:"
echo "Sitename    :" $sitenameclean
echo "Version     :" $jversion
echo "DB Name     :" $database
echo "DB User     :" $dbuser
echo "DB Password :" $password
echo "DB Host     :" $host
echo "DB Prefix   :" $prefix
echo "Path        :" `pwd`
echo ""
