#!/bin/sh

# jsitesbackup -- Find Joomla instances and backup them
# Supports all Joomla versions
# Requires jbackupstore script
#
# Backups older than 5 days are automatically cleaned
#
# Copyright 2014 Rene Kreijveld - r.kreijveld@gakijken.nl
#
# This program is free software; you may redistribute it and/or modify it.
#
# Version history
# 3.0 Initial version
# 3.1 Code rewrite
# 3.2 Modification of all echo -e statements
# 3.3 Modification of backquotes usage
# 3.4 Integrated functionality of jbackupstore into this script

# define variables
version=3.4
startdir=/home
storepath=/backups/sites
jbackupstore=/usr/local/sbin/jbackupstore
logfile=/usr/local/sbin/sitesbackup.log
savebackups=4
now=$(date +"%Y%m%d-%H%M%S")

# Determine path of script
mypath=$(cd $(dirname ${0}); pwd -P)

if [ ! -d "${storepath}" ]; then
	echo "Backup directory does not exist!"
	exit 1
fi

for dir in $(find ${startdir} -maxdepth 4 -type d -name "public_html"); do
	if [ -f ${dir}/configuration.php ]; then
		# possible joomla found
		cd ${dir}
		echo "$(date) Joomla found in ${dir}" >> ${logfile}
		# gather joomla information
		. ${mypath}/jfunctions
		# create backup
		echo "`date` Start backup ${sitename}" >> ${logfile}
		# dump the database to a .sql file
		mysqldump --skip-opt --add-drop-table --add-locks --create-options --disable-keys --lock-tables --quick --set-charset --host=${host} --user=${dbuser} --password=${password} --socket=${mysock} ${database} > ${database}.sql
		# backup site
		tar --exclude 'cache/*' -czf ${storepath}/${sitename}.${now}.tgz .htaccess *
		# cleanup datebase dump
		rm ${database}.sql
		echo "`date` End backup ${sitename}" >> ${logfile}
	fi
done

# cleanup backups older than 5 days
cd ${storepath}
find . -mtime +${savebackups} -exec rm {} \;